apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-scratch
  name: api-scratch
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: api-scratch
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-scratch
    spec:
      containers:
        - image: ko://github.com/yeahfo/cloud-native-tour/apiserver-from-scratch/cmd/apiserver
          imagePullPolicy: Always
          name: apiserver
          env:
            - name: CERT_DIR
              value: /etc/app/cert
          volumeMounts:
            - name: cert
              mountPath: /etc/app/cert
      terminationGracePeriodSeconds: 3
      volumes:
        - name: cert
          secret:
            secretName: api-svc-cert
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-scratch
  name: api-scratch
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 6443
  selector:
    app: api-scratch
---
apiVersion: v1
data:
  # kubeconfig user cert
  apiserver.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLVENDQWhHZ0F3SUJBZ0lJZU15OHd3bnhsK1F3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRFeE1qVXdOakU1TVRoYUZ3MHlOVEV4TWpVd05qSTBNVGhhTUR3eApIekFkQmdOVkJBb1RGbXQxWW1WaFpHMDZZMngxYzNSbGNpMWhaRzFwYm5NeEdUQVhCZ05WQkFNVEVHdDFZbVZ5CmJtVjBaWE10WVdSdGFXNHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEWk13ZUYKMFBwUDVBclJFazRUS0F2eGczRGZMNlZqamxIeXBNSVhjQ2hWTWVHNXZmVUpiNk9UZlR5eEk1cDF2bExaQXRRVApYSjVxUjlsRkhmQmNkbDhzVTU4ZU1KaklXcGM4S2U3aVRLZVl4ZzhBejIyRmIrd1dFUUpzWXFWWVBRZURFNEIyCnhSRGg4L2htSGNBeEsrZVY2M3RPSzhrZy9RTHlGelRLYXZpTTVnb214WktRWXlLUmVPZXg4R1FYa2pDdW1icVQKNDFBU2YwWHJyNDFmc1I3Q1BSbFdFQWhvTktSM3RZbXd4MStNQXFZdjFmZnV4WFJuRmFMeVlhN1BwY3JNZUxtOAovRE5wWjl4c0RvNDA0bGdkYm9QbGJPL2VoZVpVUDhFUVdCaGoyY24vcmVGODR2cXV3NkRRQ3UwOFhZb0g5aVFLCnRsbXRsZnRubmlReDhGSm5BZ01CQUFHalZqQlVNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUsKQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRkppTGdYaTRNMlhUT1ZvLwpyM1ovaS9MV0JDcXdNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUF0eGdxS296SFAyaGVsOVZIWHZOYlJBWE43CkRsOFZ1OWhxdmpIcjF0OG9jZiswejVjQUdLeC90ZDJEdWhqRmZKOEtxbzVUMm5wQW42T0Y4QXV5YzA5Nmp6L08Kd0xmTzhzaG1XNlZ2OVg2dG81cVVNT2J5YXF5WjlOem5YTWFkejlTVWpQN0RVanFtQUJPczgwM3VvTzc2NUd3RQp0NW9wdnQvcjBweEdTUmRsMCtnRDJYM3h6WGhGTHlnTzdEWUdhZ1pvdFpuS3l4S09kU0pSUkFPd2V4bExESjNBCnRPNTJIT2p5TXQ1T0xRRFdxMk9BN0Vsc0FxMVlZdmMxbDFHSEg5NmdnaGNjRFJiQkJkbVlBZ3pXQnhqb3ZlUXMKL3dxbFF0dUJlRGNucndsM290VEJ0Z0psS3VTSEpQNW9iQk54VFZYQWs3VVlNKy8xQk9hUVhtTXcyQ1grCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  apiserver.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBMlRNSGhkRDZUK1FLMFJKT0V5Z0w4WU53M3krbFk0NVI4cVRDRjNBb1ZUSGh1YjMxCkNXK2prMzA4c1NPYWRiNVMyUUxVRTF5ZWFrZlpSUjN3WEhaZkxGT2ZIakNZeUZxWFBDbnU0a3lubU1ZUEFNOXQKaFcvc0ZoRUNiR0tsV0QwSGd4T0Fkc1VRNGZQNFpoM0FNU3ZubGV0N1RpdkpJUDBDOGhjMHltcjRqT1lLSnNXUwprR01pa1hqbnNmQmtGNUl3cnBtNmsrTlFFbjlGNjYrTlg3RWV3ajBaVmhBSWFEU2tkN1dKc01kZmpBS21MOVgzCjdzVjBaeFdpOG1HdXo2WEt6SGk1dlB3emFXZmNiQTZPTk9KWUhXNkQ1V3p2M29YbVZEL0JFRmdZWTluSi82M2gKZk9MNnJzT2cwQXJ0UEYyS0IvWWtDclpaclpYN1o1NGtNZkJTWndJREFRQUJBb0lCQUhDQWlCTCtMY21YMnlwMApDdEROVzNKYm5PbGQ2cExvc3ZXMTlYcmljMkc5bHFmNUJxVSttRUhiQ3NiT0pFRjh0YmtHU0FkSFlCNjQzSWQ2CmZIZklNSC9yU0c0QXlnSnRPZ3pGdzZDZ0IrZVFIMUZTSCs2UURIOVpqQ0hMN3MwSHY0NWJXWjByY2hVM282QngKSkkzVHFmN3puRWpmVVN5dklRbDRqN1dSTnZEemVrZmp5S1ZCUFIzSElXMlY1d3NMOGZaMXo2NmR2N0ZTWWFKSwplck9YeXpROVZ0emVnUUtnL2FoRENmdW5FUFh4MmdZdFhOdFNhS1JEVHo4NWF0SS9FbDdEcTlYaGp5VWd5aGgvCnU1cklHSDRGTGp3bmV2dS9rQi9KcmJXMFJkVlJnekg0aFkvbFRhTUQ4UlhQNkVzN1lQRVlpaTA2RmRCc2Fjd3oKRXAzNW53RUNnWUVBNVBmZkI2aXFCS3VMWmptT1lQOG9WTXRVQ3NObWxyQ3k4UUNQUkdzUFRpY0pJZmZQZkV3Qwp5a0U0U2dDeURISTFCVjdveE82bUF2V2ZPZ0tuNWd5a0ZqQTk5WDdQTjZNT1dwYWNNcHRUVVlIWHgvcGt0aml5CjBrSEc0WnUrNnFPWUhUd0UzamdsVXRCTVVtM1hvejd0dHFUbmFZVFdSZU8yNE01RVlydXdwa0VDZ1lFQTh0ZDMKRjRkM042TUV5TkpMM2FjYXJvdS9vVVY1T1AxRldVVzJZWjJLVnczTVA3QkRFU2x2K2VoTGZTVWFTRCtucG1XQworbjdIU05tek1udkxZcThkQUMwZFNsRXJaRjVpY1NoWHk5ZU5HY2J3YmU0WW1MU0tpOWx5RnVPckJtN3JpSUphCm1kWTFMTm41ZkNHck1rR1ZVZmtldU1wSjczc0FmdG1CbFVxb1hxY0NnWUJxb3E0eWFQRFZ2L2JxSXdBV1dIODIKRG9RVGh6RnVHTmtkdUw4QWhFUGFoLytPM0ZTN2RNTVA0eFFPRXdqWkZ3OXVjdWRCWUV2Y3NQdjVEbWVYa21lUgpGZUtsUk92STQ1MjV2czc4R3E3UkZRR2oxdyswZGUrQ1VMUUpPbm5OMldic3BwazF6VHhFdDFIMFNjZlY5V2JNCld6eVRQaFIwOURxbHRDclJPTXhxZ1FLQmdFWCt5UHJsTnYyNFpVYWxKdXpxbjR3MEI3WXFXamlNK0JJMVA4NS8KSkVMWFhVbjJPajZXSFFxQlpGRGNBdWxVUDdSOGlmWTkySjhzOExQYWJ0TXcra0Qwdi82Tnl0NFJQbnF6VUNzWApKRHFMMXYwNHBhcE9UNmpqc2pqYXdvOEdKYW1oT1JBaWFBMVhmc3ZDd0orcHU2cDNEZDNob05JQU9ESlg2enZtCjJ3VDlBb0dBZDVwNE1kYnlMc2xKMDBNVlhDaDAvWUdLblloVXBGTHZUcDBMTFBhV2xRUWlNNUZGdVhCUGMzcFUKSkZJekZ6RGJPZmQrOEZ3R2tvTjNtbW5lQXRkTGVIb2JLSGF4aVNza1ZOS1Y0TjVRRERGOG5zMWo5N09JMlBWMAp0OG50RnNXRXFpY3JIMXh6U3dJcmVPTEpFYVJhR2FMQldKblZ0ellnRWZPdHZ3dmU1RWc9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: api-svc-cert
  namespace: default
type: Opaque
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.hello.yeahfo.github.io
spec:
  service:
    name: api-scratch
    namespace: default
  group: hello.yeahfo.github.io
  version: v1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
